# Compose v2 不再需要 version 字段，移除以避免警告
# HMML2 统一容器部署配置 - 前后端在同一个容器中
services:
  hmml:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hmml-unified
    ports:
      - "7999:7999"  # 后端 API 端口
      - "7998:7998"  # 前端 Web 端口
    environment:
      PYTHONUNBUFFERED: "1"
      TZ: Asia/Shanghai
    restart: unless-stopped
    networks:
      - hmml-net
    volumes:
      - hmml-data:/app/backend/data
      - hmml-logs:/app/backend/logs
      - hmml-config:/app/backend/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7999/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

networks:
  hmml-net:
    driver: bridge

volumes:
  hmml-data:
  hmml-logs:
  hmml-config:
